name: node

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        export HOME_DIR=/home/runner/work/neural-oblivious-decision-ensembles/neural-oblivious-decision-ensembles
        export NODE_DATA_DIR=$HOME_DIR/node/experiments/data
        export PYTHONPATH=$PYTHONPATH:/$HOME_DIR
        pytest -v
